# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GaborLayer": "00_core.ipynb",
         "GaborLayer.create_xy_grid": "00_core.ipynb",
         "GaborLayer.build": "00_core.ipynb",
         "GaborLayer.create_kernel": "00_core.ipynb",
         "GaborLayer.call": "00_core.ipynb",
         "GaborLayer.get_config": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://SRSteinkamp.github.io/pwc_gabor_layer/"

git_url = "https://github.com/SRSteinkamp/pwc_gabor_layer/tree/main/"

def custom_doc_links(name): return None
